Allow making pages readable, writable, and executable (#179)
As mentioned in
https://github.com/microsoft/litebox/pull/107#issuecomment-2856711807,
nodejs requires RWX pages because of JIT. It's possible to run node in
jitless mode with the flag `--jitless`. However, running wasm with
jitless node is not supported yet:
https://github.com/nodejs/node/issues/28800#issuecomment-514027732,
which causes problem when running the netlify example:

node:internal/deps/undici/undici:6340
mod = await WebAssembly.compile(llhttpWasmData ||
require_llhttp_wasm());
        ^

ReferenceError: WebAssembly is not defined
    at lazyllhttp (node:internal/deps/undici/undici:6340:9)
at lib/dispatcher/client-h1.js
(node:internal/deps/undici/undici:6429:25)
    at __require (node:internal/deps/undici/undici:6:50)
at lib/dispatcher/client.js (node:internal/deps/undici/undici:8123:21)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/dispatcher/pool.js (node:internal/deps/undici/undici:8576:18)
    at __require (node:internal/deps/undici/undici:6:50)
at lib/dispatcher/agent.js (node:internal/deps/undici/undici:8677:16)
    at __require (node:internal/deps/undici/undici:6:50)
    at lib/global.js (node:internal/deps/undici/undici:8791:17)

Node.js v24.2.0